import {
  IconAlertTriangle,
  IconArrowLeft,
  IconCategoryPlus,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconCircleX,
  IconDownload,
  IconEdit,
  IconExclamationCircle,
  IconFile,
  IconFileZip,
  IconFolder,
  IconFolderPlus,
  IconLogout2,
  IconMenu2,
  IconMoneybagMinus,
  IconMoneybagPlus,
  IconSearch,
  IconSettings,
  IconTrash,
  IconX,
} from "@tabler/icons-react";

export const Icons = {
  moneybagPlus: IconMoneybagPlus,
  moneybagMinus: IconMoneybagMinus,
  categoryPlus: IconCategoryPlus,
  setting: IconSettings,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  x: IconX,
  folderPlus: IconFolderPlus,
  circleX: IconCircleX,
  folder: IconFolder,
  file: IconFile,
  search: IconSearch,
  fileZip: IconFileZip,
  trash: IconTrash,
  arrowLeft: IconArrowLeft,
  exclamationCircle: IconExclamationCircle,
  circleCheck: IconCircleCheck,
  menu: IconMenu2,
  edit: IconEdit,
  download: IconDownload,
  triangleAlert: IconAlertTriangle,
  logout: IconLogout2,
};
